# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11w8O8xKdcCgA58g6BbqJkl3IoqqXzsZj

DATA ANALYST INTERNSHIP
Task 1: Data Cleaning and Preprocessing

Objective: Clean and prepare a raw dataset (with nulls, duplicates, inconsistent formats).

Dataset Taken: Customer Personality Analysis
"""

import pandas as pd

import kagglehub

# Download latest version
path = kagglehub.dataset_download("imakash3011/customer-personality-analysis")

print("Path to dataset files:", path)

data= pd.read_csv(path + "/marketing_campaign.csv", sep="\t")
data



print(data.isnull().sum())

data_cleaned = data.dropna(subset=['Income'])
print("Shape after dropping rows with null values in 'Income' column:", data_cleaned.shape)

#verifying null values are ommmited
print(data_cleaned.isnull().sum())

#removing duplicates
data_cleaned = data_cleaned.drop_duplicates()
print("Shape after removing duplicate rows:", data_cleaned.shape)

print("Unique values in Education column:", data_cleaned['Education'].unique())
print("Unique values in Marital_Status column:", data_cleaned['Marital_Status'].unique())

#checking datatypes
print(data_cleaned.info())

print(data_cleaned.head())



data_cleaned['Dt_Customer'] = pd.to_datetime(data_cleaned['Dt_Customer'], format='%d-%m-%Y')
print(data_cleaned.info())

data_cleaned.columns = data_cleaned.columns.str.lower().str.replace(' ', '_')
print("Cleaned column headers:", data_cleaned.columns)

display(data_cleaned)